region="europe-west2"
zone="europe-west2-a"
google-provider-version="3.7.0"
billing-account="0177D8-2B9095-D16093"
automation-service-account="grb-gcp-devops@grb-gcp-devops.iam.gserviceaccount.com"
application-container-image="gcr.io/grb-gcp-devops/grb-gcp-devops-helloworld:latest"
application-name="helloworldapp"
container-port="12333"
