#
#
#
substitutions:
  _TERRAFORM_VERSION: '0.12.20'
  _TERRAFORM_VERSION_SHA256SUM: '46bd906f8cb9bbb871905ecb23ae7344af8017d214d735fbb6d6c8e0feb20ff3'
  _PROJECT_BASE_NAME: 'k8s-poc-dev'
  _BACKEND_BUCKET: 'grb-gcp-devops-terraform'
  _CLUSTER_NAME: "k8s-cluster-1"

timeout: '1200s'
steps:

# Retrieve Cluster Credentials
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'container'
  - 'clusters'
  - 'get-credentials'
  - '${_CLUSTER_NAME}'

# Terraform init
- name: 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  dir: 'kubernetes'
  args:
  - 'init'
  - '-input=false'
  - '-var-file=tfvars/${_ENVIRONMENT}.tfvars'
  - '-backend-config=bucket=${_BACKEND_BUCKET}'
  - '-backend-config=prefix=terraform/${_PROJECT_BASE_NAME}-${_ENVIRONMENT}/kubernetes/state/'
  env:
  - "TF_VAR_project-base-name=${_PROJECT_BASE_NAME}"
  - "TF_VAR_environment=${_ENVIRONMENT}"
  - "TF_VAR_container-cluster-name=${_CLUSTER_NAME}"
  - "TF_IN_AUTOMATION=true"


# Terraform Plan
- name: 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  dir: 'kubernetes'
  args:
  - 'plan'
  - '-input=false'
  - '-var-file=tfvars/${_ENVIRONMENT}.tfvars'
  - '-destroy'
  - '-compact-warnings'
  - '-out=plan.tfplan'
  env:
  - "TF_VAR_project-base-name=${_PROJECT_BASE_NAME}"
  - "TF_VAR_environment=${_ENVIRONMENT}"
  - "TF_VAR_container-cluster-name=${_CLUSTER_NAME}"
  - "TF_IN_AUTOMATION=true"

# Terraform Show
- name: 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  dir: 'kubernetes'
  args:
  - 'show'
  - '-no-color'
  - 'plan.tfplan'
  - '> tf-plan-${_PROJECT_BASE_NAME}-${BUILD_ID}.txt'
  env:
  - "TF_IN_AUTOMATION=true"

# Terraform Apply
- name: 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  dir: 'kubernetes'
  args:
  - 'destroy'
  - '-input=false'
  - '-var-file=tfvars/${_ENVIRONMENT}.tfvars'
  - '-auto-approve'
  env:
  - "TF_VAR_project-base-name=${_PROJECT_BASE_NAME}"
  - "TF_VAR_environment=${_ENVIRONMENT}"
  - "TF_VAR_container-cluster-name=${_CLUSTER_NAME}"
  - "TF_IN_AUTOMATION=true"

# Does not seem to be able to find the output plain text plan file
#artifacts:
#  objects:
#    location: 'gs://${_BACKEND_BUCKET}/terraform/${_PROJECT_BASE_NAME}-${_ENVIRONMENT}/artifacts/'
#    paths: ['infrastructure/tf-plan-${_PROJECT_BASE_NAME}-${BUILD_ID}.txt']
