substitutions:
  _TERRAFORM_VERSION: "0.12.20"
  _TERRAFORM_VERSION_SHA256SUM: "46bd906f8cb9bbb871905ecb23ae7344af8017d214d735fbb6d6c8e0feb20ff3"

options:
  logStreamingOption: STREAM_ON
  logging: GCS_ONLY

steps:

# Clone the terraform builder repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'clone'
  - 'https://github.com/GoogleCloudPlatform/cloud-builders-community'

# Build a Terraform-Builder container image which uses the specified Terraform binary version
- name: 'gcr.io/cloud-builders/gcloud'
  dir: 'terraform'
  args:
  - 'builds'
  - 'submit'
  - '--config=cloudbuild.yaml'
  - '--substitutions=_TERRAFORM_VERSION="${_TERRAFORM_VERSION}",_TERRAFORM_VERSION_SHA256SUM="${_TERRAFORM_VERSION_SHA256SUM}"'
