substitutions:
  _TERRAFORM_VERSION: '0.12.24'
  _TERRAFORM_VERSION_SHA256SUM: '602d2529aafdaa0f605c06adb7c72cfb585d8aa19b3f4d8d189b42589e27bf11'

options:
  logStreamingOption: STREAM_ON
  logging: GCS_ONLY

steps:

# Clone the terraform builder repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'clone'
  - 'https://github.com/GoogleCloudPlatform/cloud-builders-community'

# Build a Terraform-Builder container image which uses the specified Terraform binary version
- name: 'gcr.io/cloud-builders/gcloud'
  dir: 'cloud-builders-community/terraform'
  args:
  - 'builds'
  - 'submit'
  - '--config=cloudbuild.yaml'
  - '--substitutions=_TERRAFORM_VERSION=${_TERRAFORM_VERSION},_TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}'
