#
#
#
substitutions:
  _TERRAFORM_VERSION: '0.12.20'
  _TERRAFORM_VERSION_SHA256SUM: '46bd906f8cb9bbb871905ecb23ae7344af8017d214d735fbb6d6c8e0feb20ff3'
  _PROJECT_BASE_NAME: 'grb-gcp-devops-k8s-poc'
  _BACKEND_BUCKET: 'grb-gcp-devops-terraform'


steps:

# Terraform init
- name: 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  dir: 'infrastructure'
  args:
  - 'init'
  - '-input=false'
  - '-var-file=tfvars/${_ENVIRONMENT}.tfvars'
  - '-backend-config=bucket=${_BACKEND_BUCKET}'
  - '-backend-config=prefix=terraform/${_PROJECT_BASE_NAME}-${_ENVIRONMENT}/state/'
  env:
  - "TF_VAR_project-base-name=${_PROJECT_BASE_NAME}"
  - "TF_VAR_environment=${_ENVIRONMENT}"
  - "TF_IN_AUTOMATION=true"


# Terraform Plan
- name: 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  dir: 'infrastructure'
  args:
  - 'plan'
  - '-input=false'
  - '-var-file=tfvars/${_ENVIRONMENT}.tfvars'
  - '-compact-warnings'
  - '-out=plan.tfplan'
  env:
  - "TF_VAR_project-base-name=${_PROJECT_BASE_NAME}"
  - "TF_VAR_environment=${_ENVIRONMENT}"
  - "TF_IN_AUTOMATION=true"


# Terraform Show
- name: 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  dir: 'infrastructure'
  args:
  - 'show'
  - '-no-color'
  - 'plan.tfplan'
  - '> tf-plan-${_PROJECT_BASE_NAME}-${BUILD_ID}.txt'
  env:
  - "TF_IN_AUTOMATION=true"



# Terraform Apply
- name: 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  dir: 'infrastructure'
  args:
  - 'apply'
  - '-input=false'
  - '-var-file=tfvars/${_ENVIRONMENT}.tfvars'
  - '-auto-approve'
  env:
  - "TF_VAR_project-base-name=${_PROJECT_BASE_NAME}"
  - "TF_VAR_environment=${_ENVIRONMENT}"
  - "TF_IN_AUTOMATION=true"

# Does not seem to be able to find the output plain text plan file
# regardless of the path
#artifacts:
#  objects:
#    location: 'gs://${_BACKEND_BUCKET}/terraform/${_PROJECT_BASE_NAME}-${_ENVIRONMENT}/artifacts/'
#    paths: ['infrastructure/tf-plan-${_PROJECT_BASE_NAME}-${BUILD_ID}.txt']
