#
#
#
substitutions:
  _TERRAFORM_VERSION: '0.12.20'
  _TERRAFORM_VERSION_SHA256SUM: '46bd906f8cb9bbb871905ecb23ae7344af8017d214d735fbb6d6c8e0feb20ff3'
  _BACKEND_BUCKET: 'grb-gcp-devops-terraform'
  _BACKEND_PREFIX: 'terraform/${PROJECT_ID}-${_ENVIRONMENT}/state/'
steps:

# Terraform init
- name: 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  dir: 'infrastructure'
  args:
  - 'init'
  - '-var-file=tfvars/${_ENVIRONMENT}.tfvars'
  - '-backend-config=bucket=${_BACKEND_BUCKET}'
  - '-backend-config=prefix=${_BACKEND_PREFIX}'
  env:
  - "TF_VAR_project-common-name=${PROJECT_ID}"
  - "TF_VAR_environment=${_ENVIRONMENT}"

# Terraform Plan
- name: 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  dir: 'infrastructure'
  args:
  - 'plan'
  - '-var-file=tfvars/${_ENVIRONMENT}.tfvars'
  - '-compact-warnings'
  - '-detailed-exitcode'
  - '-out=plan.tfplan'
  env:
  - "TF_VAR_project-common-name=${PROJECT_ID}"
  - "TF_VAR_environment=${_ENVIRONMENT}"

# Terraform Show
- name: 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  dir: 'infrastructure'
  args:
  - 'show'
  - '-var-file=tfvars/${_ENVIRONMENT}.tfvars'
  - '-no-color'
  - 'plan.tfplan'
  - '> tf-plan-${PROJECT_ID}-${BUILD_ID}'
  env:
  - "TF_VAR_project-common-name=${PROJECT_ID}"
  - "TF_VAR_environment=${_ENVIRONMENT}"

# Terraform Apply
- name: 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  dir: 'infrastructure'
  args:
  - 'apply'
  - '-var-file=tfvars/${_ENVIRONMENT}.tfvars'
  - '-auto-approve'
  env:
  - "TF_VAR_project-common-name=${PROJECT_ID}"
  - "TF_VAR_environment=${_ENVIRONMENT}"
